### ISSUE TITLE
Ability to invalidate the entire cache?

### ISSUE THREAD

**Issue by jamesbirtles** [moka-rs/moka#10]
A use case has come up where I'd like to invalidate the entire cache (or perhaps invalidate based on a predicate on the values). I'm not seeing any way to do this at the moment. I am using the future based cache.

**Comment by tatsuya6502** [comment]
Hi. I started to implement `invalidate_all` method, which invalidate the entire cache. (#11)

Once I am done with it, I will start to work on `invalidate_entries_if` method, which takes a predicate and invalidate entries that meet the predicate.

I will let you know when they are ready.

**Comment by UnwrittenFun** [comment]
Awesome! 🎉

**Comment by tatsuya6502** [comment]
@UnwrittenFun &mdash; I just published [Moka 0.3.0](https://crates.io/crates/moka/0.3.0) to crates.io. It has `invalidate_all` method and I hope you will like it. ([API doc](https://docs.rs/moka/0.3.0/moka/future/struct.Cache.html#method.invalidate_all))

I will keep this issue open until I finish implementing `invalidate_entries_if` method.

**Comment by tatsuya6502** [comment]
> I will keep this issue open until I finish implementing `invalidate_entries_if` method.

Finally, I finished implementing this method (PR #12). It takes a predicate and invalidate entries that satisfy the predicate. (`key: &K` and `value: &V` are passed to the predicate)  The invalidation is processed by a background thread and client reads/writes will not be blocked while running the invalidation.

I am running some load tests now. If they go well, I will merge the PR and release Moka v0.4.0.
