### ISSUE TITLE
Check for presence of key

### ISSUE THREAD

**Issue by razaqq** [moka-rs/moka#107]
Would it be possible to add a function to check if a key is present without resetting the idle timer?
Pretty much exactly like
https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.contains_key

**Comment by tatsuya6502** [comment]
Thanks for posting the request. It would be a nice addition to the cache. I am working on it via #110.

**Comment by tatsuya6502** [comment]
I just published Moka [v0.8.1](https://crates.io/crates/moka/0.8.1) to crates.io. It has `contains_key` method in all cache flavors.

**Comment by razaqq** [comment]
very nice, thanks alot!
