### ISSUE TITLE
[feature request] add `Cache::get_with_if(&self, key: &K, fallback: Fut, cond: Fn(&V) -> bool) -> V` method

### ISSUE THREAD

**Issue by ClSlaid** [moka-rs/moka#123]
I'm building a cache whose entries have their own standalone TTL. However `moka` supports global TTL and IDLE only. So I'm here to propose a new method `Cache::get_with_if(&self, key: &K, fallback: Fut, cond: Fn(&V) -> bool) -> V`

The function works like `Cache::get_with(&self, key: &K, init: Fut) -> V`, but when the key does not exist or `cond(&V)` is true, the `init` clojure will be called to initialize the value.

**Comment by tatsuya6502** [comment]
Thank you for proposing `get_with_if` method. I think it will be easy to implement. Let me work on it.

> I'm building a cache whose entries have their own standalone TTL. However `moka` supports global TTL and IDLE only.

You are right. Per-entry expiration is on [our roadmap](https://github.com/orgs/moka-rs/projects/1/views/1) but currently scheduled very late. (The item 10: "(post v1.0) feat: The variable (per-entry) expiration, using a hierarchical timer wheel")  I will probably give it more priority. But anyway, I will implement `get_with_if` for now.

**Comment by tatsuya6502** [comment]
Hi @ClSlaid — I have published [Moka v0.8.4](https://crates.io/crates/moka/0.8.4) to crates.io with the `get_with_if` method. Thanks!
