### ISSUE TITLE
how to use build_with_hash?

### ISSUE THREAD

**Issue by arifd** [moka-rs/moka#214]
Hello! Thank you for this fantastic crate!!

Admittedly, I've never used an alternative hasher before so maybe I'm dong something wrong, but If I try with FxHasher, I get this:
```rust
error[E0308]: mismatched types
   --> foo/src/main.rs:28:28
    |
28  |         .build_with_hasher(FxBuildHasher::default())
    |          ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `RandomState`, found struct `BuildHasherDefault`
    |          |
    |          arguments to this function are incorrect
    |
    = note: expected struct `RandomState`
               found struct `BuildHasherDefault<FxHasher>`
```

So then i tried with ahash because, [in one of the issues](https://github.com/moka-rs/moka/issues/64) i found such an example
but then I get:
```rust
error[E0308]: mismatched types
    --> foo/src/main.rs:27:28
     |
27   |         .build_with_hasher(ahash::RandomState::default())
     |          ----------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::collections::hash_map::RandomState`, found struct `ahash::RandomState`
     |          |
     |          arguments to this function are incorrect
     |
```
Am I doing something wrong?

**Comment by tatsuya6502** [comment]
Hi. Thank you for using Moka.

`Cache` has three generic types: mandatory `K`, `V`, and optional `S`. `S` is the type of the build hasher and the default is `std::collections::hash_map::RandomState`.

```rust
pub struct Cache<K, V, S = RandomState> { /* private fields */ }
```

You probably have a type annotation `Cache<KeyType, ValueType>` for your cache somewhere in your code. But when you use a build hasher other than the default, you need to specify the type of `S`. For example, `Cache<KeyType, ValueType, BuildHasherDefault<FxHasher>>>`.

Here are bad and good examples:

The following code snippet will cause a type mismatch error:

```rust
use moka::sync::Cache;
use fxhash::FxBuildHasher;

fn main() {
    let cache = Cache::builder().build_with_hasher(FxBuildHasher::default());
    my_fun(&cache);
}

// Use the default type `RandomState` for `S`.
fn my_fun(cache: &Cache<String, String>) {
    cache.insert("key".to_string(), "value".to_string());
}
```

```console
error[E0308]: mismatched types
  --> src/bin/main2.rs:8:12
   |
8  |     my_fun(&cache);
   |     ------ ^^^^^^ expected struct `RandomState`, found struct `BuildHasherDefault`
   |     |
   |     arguments to this function are incorrect
   |
   = note: expected reference `&moka::sync::Cache<String, String>`
              found reference `&moka::sync::Cache<_, _, BuildHasherDefault<FxHasher>>`
```

The following code snippet should compile:

```rust
use moka::sync::Cache;
use std::hash::BuildHasherDefault;
use fxhash::{FxHasher, FxBuildHasher};

fn main() {
    let cache = Cache::builder().build_with_hasher(FxBuildHasher::default());
    my_fun(&cache);
}

// Specify the correct `S` type.
fn my_fun(cache: &Cache<String, String, BuildHasherDefault<FxHasher>>) {
    cache.insert("key".to_string(), "value".to_string());
}
```

It the current doc, it is not very obvious that you need to specify the type of `S` when you use a build hasher other than the default. I will update the doc to make it more clear, with an example like the above.

**Comment by arifd** [comment]
Ah good catch!! And perfect response. Thanks

**Comment by tatsuya6502** [comment]
Closing. Added code samples to the doc via #216 for upcoming [v0.9.7](https://github.com/moka-rs/moka/milestone/30) release.
