### ISSUE TITLE
[BUG] `usize` overflow on big cache capacity

### ISSUE THREAD

**Issue by GrandChaman** [moka-rs/moka#25]
Hello,

First of all thank you for the very nice work !

There seems to be a multiply overflow that could be handled at the line referenced below.

https://github.com/moka-rs/moka/blob/76b06af686c5ecaa913abf1acb46e45fc4f0a95c/src/sync/base_cache.rs#L395

This could be done either by returning an error type, or by maxing the value of the cache capacity to `usize::max_value() / 32`

**Comment by tatsuya6502** [comment]
This has been addressed by #28. I will release Moka v0.5.2 soon.
