### ISSUE TITLE
feature request: remove method

### ISSUE THREAD

**Issue by vdhanan** [moka-rs/moka#255]
First, thanks for this awesome crate! It's been really helpful for us.

I was wondering if it would be possible to add a `remove` method to [moka](https://docs.rs/moka/0.10.2/moka/index.html)::[future](https://docs.rs/moka/0.10.2/moka/future/index.html)::[Cache](https://docs.rs/moka/0.10.2/moka/future/struct.Cache.html#) that removes a key from the cache, returning the value at the key if the key was previously in the cache.

Right now I am manually invalidating keys after calling `get()`, but a single method that could do both operations would be pretty handy.

**Comment by tatsuya6502** [comment]
Hi. Thank you for suggesting the `remove` method. I am adding it to `future` and `sync` caches via  #258.

It will be included in upcoming v0.11.0 release.

**Comment by tatsuya6502** [comment]
Just FYI, I just published moka [v0.11.0](https://crates.io/crates/moka/0.11.0) to crates.io.
