### ISSUE TITLE
Implement Serialize trait for debugging webserver?

### ISSUE THREAD

**Issue by peter-scholtens** [moka-rs/moka#273]
Although the trait `Debug` is implemented, allowing debugging using console/file output, I would like to use the `Serialize` trait for the **moka::{sync,future}::Cache** too. The reason for this is the following: a webserver built with [axum](https://docs.rs/axum/latest/axum/#responses) can support JSON [responses](https://docs.rs/http/0.2.9/http/response/struct.Response.html) which then could generate a special page e.g. `http://example.com/cachecontent` to peek inside the cache.
Optionally, fields that are cumbersome to include can be skipped with `#[serde(skip_serializing)]`

**Comment by tatsuya6502** [comment]
Hi. Yeah. There is no convenient way to do it now. You can still create a JSON containing cache contents using iterator:

https://github.com/moka-rs/moka/discussions/235

Please read the "Limitations" in the message above. The `Debug` implementation uses the iterator too, so it has the same limitations.

**Comment by peter-scholtens** [comment]
Sounds like a good solution! Sorry I overlooked #235 while scanning (past) issue list. The solutions and examples are good enough to help me further. As I now realize, serializing all data may not be handy too, which removes the need for me to have this trait.
