### ISSUE TITLE
Crash in iOS

### ISSUE THREAD

**Issue by ssrlive** [moka-rs/moka#406]
When I upgrade moka from version 0.11 to 0.12, my app crashed in iOS, but this issue not appears in others platforms. 
I don't know the reason.

https://github.com/ShadowsocksR-Live/overtls/commit/6724ec408d7fe1d901c33efb2e245535fd296eeb

![image](https://github.com/moka-rs/moka/assets/30760636/e724feff-b265-430a-a7b3-d03c38e81661)

**Comment by tatsuya6502** [comment]
Thank you for reporting the issue.

The crash message "bad instruction" implies some of the processors used in the iOS devices do not support reading from the `cntvct_el0` register. `moka` v0.11 and v0.12 depend on `quanta` v0.11 and v0.12 respectively. And `quanta` v0.12 tries to read from `cntvct_el0` register on arm64 processors.

I will report this to `quanta` crate and see if they can workaround it.

**Comment by ssrlive** [comment]
I have reported. https://github.com/metrics-rs/quanta/issues/101

**Comment by ssrlive** [comment]
fixed
