### ISSUE TITLE
CI:  pinning `proc-macro2` in test(nightly) results in dependency resolution failure.

### ISSUE THREAD

**Issue by xuehaonan27** [moka-rs/moka#461]
I have opened a PR to `moka`.
As shown in the figure, CI failed because of pinning `proc-macro2` to 1.0.63, but the cargo decides that `proc-macro2` should be higher than 1.0.74.
Is pinning the dependency necessary for testing? Can we remove this pinning or just upgrade it into higher version?
Or maybe I'm making some mistakes. If so, please tell me so I can make some changes, thank you!

<img width="1105" alt="截屏2024-10-10 11 53 47" src="https://github.com/user-attachments/assets/704c9300-8beb-433c-a1ed-78ca2b510013">

**Comment by tatsuya6502** [comment]
Sorry for a late reply; I was busy with work for the past few months.

As you suggested, I unpined `proc-macro2` in the CI by #463, and this should fix the issue. I do not rememeber the exact reasons but pinning `proc-macro2` was necessary in the past to avoid build failures ([#354](https://github.com/moka-rs/moka/pull/354/files#diff-0935df9db0de0478f4425f359074c292332a44681946fb853ca3c62f5a3b2b6fR6), [#361](https://github.com/moka-rs/moka/pull/361/files#diff-0935df9db0de0478f4425f359074c292332a44681946fb853ca3c62f5a3b2b6fR6)). It seems they have been resolved.
